name: Run 3LC tests

on:
  pull_request:
    branches:
      - tlc-integration

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.28"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run ruff formatter
        run: uvx ruff format --check ultralytics/utils/tlc

      - name: Install dependencies
        run: |
          uv pip install . pacmap==0.7.3 pytest

      - name: Run tests
        run: |
          export $(echo ${{ secrets.VARIABLE_NAME }})=${{ secrets.VARIABLE_VALUE }}
          export $(echo ${{ secrets.RUNTIME_NAME }})=${{ secrets.RUNTIME_VALUE }}
          export TLC_API_KEY=${{ secrets.TLC_API_KEY }}
          uv run --no-project pytest tests/test_3lc.py